apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-servicemonitor
  namespace: newmonitoring
  labels:
    release: newmon-prometheus
spec:
  selector:
    matchLabels:
      app: springboot
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
      scheme: http
      honorLabels: true
